<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace and folder name.
    | Edit with caution !!!!
    |
    */

    'namespace' => 'Modules',

    /*
    |--------------------------------------------------------------------------
    | Module Base Folder
    |--------------------------------------------------------------------------
    |
    | Base folder name for modules.
    |
    */
    'folder' => 'modules',

    /*
    |--------------------------------------------------------------------------
    | Module Stubs
    |--------------------------------------------------------------------------
    |
    | Default module stubs.
    |
    */

    'paths' => [
        /*
        |--------------------------------------------------------------------------
        | Modules path
        |--------------------------------------------------------------------------
        |
        | This path used for save the generated module. This path also will be added
        | automatically to list of scanned folders.
        |
        */

        'modules' => base_path('modules'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Seed Orchestration
    |--------------------------------------------------------------------------
    |
    | Configuration for module seed orchestration.
    |
    */
    'seeds' => [
        /*
        | Enable automatic seed orchestration
        */
        'enabled' => true,

        /*
        | Run module seeds after main database seeder
        */
        'run_after_main' => true,

        /*
        | Throw exception on circular dependencies
        */
        'strict_dependencies' => true,

        /*
        | Default priority for seeders (if not specified)
        */
        'default_priority' => 100,
    ],

    /*
    |--------------------------------------------------------------------------
    | Module Auto Discovery
    |--------------------------------------------------------------------------
    |
    | Enable automatic module discovery and registration.
    |
    */
    'discovery' => [
        'enabled' => true,
        'cache' => true,
    ],


    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    |
    */

    'composer' => [
        'vendor' => 'erlandmuchasaj',
        'author' => [
            'name' => 'Erland Muchasaj',
            'email' => 'erland.muchasaj@gmail.com',
        ],
        'composer-output' => false,
    ],
];
